2nd task
js-tasks-ru/jsbasic-20230428_vadim700 pull request #2
Opened 2023-05-03 16:39 UTC by Vadim700

2023-05-03 16:39 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-04 09:15 UTC, SinimaWath requested changes

2023-05-04 09:15 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return false;
`return (name !== null) && (name.length >= 4) && (!name.includes(' '))` - так как результат операции и так boolean, то есть if не нужен

2023-05-04 09:15 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
`return result.includes('1xbet') || result.includes('xxx')` - так как результат операции и так boolean, то есть if не нужен

2023-05-04 16:39 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-05 10:14 UTC, SinimaWath approved these changes

2023-05-05 10:15 UTC, merged