3rd module
js-tasks-ru/jsbasic-20230428_vadim700 pull request #4
Opened 2023-05-14 16:33 UTC by Vadim700

2023-05-14 16:34 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-15 11:42 UTC, SinimaWath requested changes

2023-05-15 11:42 UTC, SinimaWath commented on 3-module/4-task/index.js
> +      .join('')
тут вместо вставки символа: `\n`. Понятней и проще будет использовать: `.join('\n')`

2023-05-15 17:54 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-16 11:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-17 06:51 UTC, SinimaWath approved these changes

2023-05-17 06:52 UTC, merged